services:
  server:
    build: ./app
    ports:
      - "127.0.0.1:2229:2222"
    restart: unless-stopped
    develop:
      watch:
      - action: rebuild
        path: .
        target: /app
    environment:
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      KEYDB_PASSWORD: "${KEYDB_PASSWORD}"
    depends_on:
      db:
        condition: service_healthy
      keydb:
        condition: service_healthy
       
  keydb:
    image: eqalpha/keydb
    command: keydb-server /etc/keydb/keydb.conf --save 60 1 --requirepass $KEYDB_PASSWORD
    ports:
      - "127.0.0.1:6379:6379"
    # volumes:
    #   - ./keydb/data:/data
    environment:
      KEYDB_PASSWORD: "${KEYDB_PASSWORD}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  db:
    image: postgres:14-alpine
    ports:
      - "127.0.0.1:5432:5432"
    # volumes: # Persistence disabled for dev reason
      # - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s
# volumes:
  # db:
    # driver: local